Repository FromDoppler/Wordpress-Plugin-Doppler, pull requests merged in 2024-02, with the labels that each got.

#69 DOI-451
  public/js/doppler-form-public.js
Labels: size/XS

#70 [DOI-461] Form fields format
  includes/helpers/Form_Helper.php
  public/js/doppler-form-public.js
Labels: size/L

#71 [DOI-461] bug fixing
  admin/doppler-admin.php
  admin/js/doppler-form-admin.js
  readme.txt
Labels: size/XXL

#72 [DOI-1132] Update tested up to version
  readme.txt
Labels: size/XS

#73 [DOI-1178] Replace tinyMCE.getContent() function for value of element
  admin/js/doppler-form-admin.js
Labels: size/XS

#74 [DOI-1198] Fix for double form submision
  includes/helpers/Form_Helper.php
  public/js/doppler-form-public.js
Labels: size/L

#75 [No ticket] Update app version to 2.3.7
  doppler-form.php
  readme.txt
Labels: size/S
